# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb55736e180062bdcb1d80bbaf67731be523fde35fdeaed309a4fe503906914d69f185f92f7bf22fa10116273963d5a6b90dc9a9b1e8fae7be0b818ee8f63281

test:
  secret_key_base: 9444ca7b7e283522bf4efb34e83f3fac51f67c2f381b72d4b545f67ebe3aa0156a6054674a9c9f96c348db873e8fe5ee1aec037ed97dd19444f5c182cd1572c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
